/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/AgUSD.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <PerspectiveCamera makeDefault={false} far={2} near={0} fov={34.52} position={[0.08, 0.69, 0.43]} rotation={[-1.01, 0.14, 0.22]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Clean Gold']} scale={[1, 0.1, 1]} />
      <mesh geometry={nodes.Torus.geometry} material={materials['Clean Gold']} position={[0, 0.03, 0]} rotation={[0, 0, -Math.PI]} scale={[1, 0.75, 1]} />
      <group position={[-0.04, 0.02, 0.04]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes['TextMesh#'].geometry} material={materials['Default Material 6']} />
        <mesh geometry={nodes['TextMesh#_1'].geometry} material={materials['Default Material 6']} />
        <mesh geometry={nodes['TextMesh#_2'].geometry} material={materials['Default Material 6']} />
      </group>
    </group>
  )
}

useGLTF.preload('/AgUSD.glb')
